---
  - name: "Challenge answers"
    hosts: localhost

    tasks:

      - name: "test reachability"
        ping:

      - name: "find module"
        find:
          name: ~/challenges
          file_type: file