---
  - name: "React with Change Example"
    hosts: logicservers
    strategy: free

    tasks:

    - name: "Install Nginx"
      debug:
        msg: "Install nginx on: {{ inventory_hostname }}"

    - name: "Upgrade Nginx"
      debug:
        msg: "Upgrade Nginx on: {{ inventory_hostname }}"

    - name: "Configure Nginx"
      debug:
        msg: "Start {{ inventory_hostname }}"
      notify: restart nginx
      changed_when: True